package org.example.scip.storage;

/**
 * Status of a SCIP index through the processing pipeline.
 */
public enum IndexStatus {
    /**
     * SCIP file has been generated by the indexer.
     */
    CREATED,

    /**
     * SCIP protobuf has been successfully parsed.
     */
    PARSED,

    /**
     * Index has been mapped to graph model (symbols, references).
     */
    MAPPED,

    /**
     * Data has been stored in Neo4j database.
     */
    STORED,

    /**
     * Processing failed at some stage.
     */
    FAILED
}
